import { Layers } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Foldera',
  description: 'Terms governing use of Foldera.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <nav className="border-b border-white/5 py-6 px-6">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <a href="/" className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-xl bg-white text-black flex items-center justify-center">
              <Layers className="w-4 h-4 fill-black" />
            </div>
            <span className="text-lg font-black tracking-tighter uppercase">Foldera</span>
          </a>
          <a href="/" className="text-xs font-black uppercase tracking-[0.2em] text-zinc-500 hover:text-white transition-colors">
            Back to home
          </a>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-20">
        <h1 className="text-4xl font-black tracking-tight mb-4">Terms of Service</h1>
        <p className="text-zinc-400 text-sm mb-12">Last updated: March 2026</p>

        <div className="space-y-10 text-zinc-300 text-sm leading-relaxed">
          <section>
            <h2 className="text-white text-lg font-bold mb-3">Service</h2>
            <p>
              Foldera is an AI-powered briefing assistant that processes connected email and
              calendar data to produce daily actionable directives. By using the service,
              you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-bold mb-3">Accounts</h2>
            <p>
              You must authenticate via Google or Microsoft OAuth to use Foldera.
              You are responsible for maintaining the security of your connected accounts.
              One account per person.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-bold mb-3">Acceptable use</h2>
            <p>
              Do not use Foldera to process data you do not have the right to access,
              attempt to reverse-engineer the AI models, or abuse the API endpoints.
              We reserve the right to suspend accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-bold mb-3">Billing</h2>
            <p>
              Foldera Pro is billed monthly at $99/month after a 14-day free trial.
              You can cancel at any time from Dashboard &rarr; Settings. Cancellation
              takes effect at the end of the current billing period. No refunds for
              partial months.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-bold mb-3">AI-generated content</h2>
            <p>
              Directives and drafts are generated by AI based on your data. While we
              strive for accuracy, you are responsible for reviewing and approving any
              actions before they execute. Foldera is not liable for actions taken
              based on AI-generated recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-bold mb-3">Data and termination</h2>
            <p>
              You can delete your account and all associated data at any time.
              Upon cancellation, data is retained for 30 days before permanent deletion.
              We may terminate accounts that violate these terms with reasonable notice.
            </p>
          </section>

          <section>
            <h2 className="text-white text-lg font-bold mb-3">Contact</h2>
            <p>
              Questions about these terms? Email <span className="text-cyan-400">legal@foldera.ai</span>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
