// lib/gmail-service.ts
import { google } from 'googleapis';

// --- The Helper Functions ---

export async function getGmailClient(userId: string) {
  // In a real app, you fetch these from your DB using userId
  // For now, we assume the environment variables are set for a single user mode
  const oauth2Client = new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID,
    process.env.GOOGLE_CLIENT_SECRET,
    process.env.NEXT_PUBLIC_APP_URL + "/api/auth/callback/google"
  );

  // You would normally pull the REFRESH_TOKEN from the DB here
  // oauth2Client.setCredentials({ refresh_token: dbUser.refresh_token });
  
  return google.gmail({ version: 'v1', auth: oauth2Client });
}

export function extractPlainBody(payload: any): string {
  let body = '';
  if (payload.parts) {
    for (const part of payload.parts) {
      if (part.mimeType === 'text/plain' && part.body?.data) {
        body += Buffer.from(part.body.data, 'base64').toString('utf-8');
      } else if (part.parts) {
        body += extractPlainBody(part); // Recursive
      }
    }
  } else if (payload.body?.data) {
    body = Buffer.from(payload.body.data, 'base64').toString('utf-8');
  }
  return body;
}

export function isUserMessage(email: any, userEmail: string): boolean {
  const fromHeader = email.payload.headers.find((h: any) => h.name === 'From');
  return fromHeader ? fromHeader.value.includes(userEmail) : false;
}

export async function generateDraftForThread(threadId: string, userId: string) {
  // Your AI Logic would go here
  return {
    subject: "Re: Meeting",
    body: "Draft generated by Foldera."
  };
}

