/**
 * POST /api/conviction/execute
 * Body: { action_id: string, decision: "approve" | "skip" }
 *
 * On approve of email_compose / email_reply actions, sends the email via
 * Gmail or Outlook based on the user's connected provider.
 */

import { NextResponse }      from 'next/server';
import { getServerSession }  from 'next-auth';
import { createClient }      from '@supabase/supabase-js';
import { getAuthOptions }    from '@/lib/auth/auth-options';
import { sendGmailEmail }    from '@/lib/integrations/gmail-client';
import { sendOutlookEmail }  from '@/lib/integrations/outlook-client';
import { hasIntegration }    from '@/lib/auth/token-store';

export const dynamic = 'force-dynamic';

function getSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}

export async function POST(request: Request) {
  let userId: string | undefined;
  const ingestSecret = request.headers.get('x-ingest-secret');
  if (ingestSecret) {
    if (ingestSecret !== process.env.INGEST_API_KEY) {
      return NextResponse.json({ error: 'Invalid ingest secret' }, { status: 401 });
    }
    userId = process.env.INGEST_USER_ID;
  } else {
    const session = await getServerSession(getAuthOptions());
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    userId = process.env.INGEST_USER_ID ?? session.user.id;
  }
  if (!userId) return NextResponse.json({ error: 'User ID not resolved' }, { status: 500 });

  const body = await request.json().catch(() => ({}));
  const { action_id, decision } = body as { action_id?: string; decision?: string };

  if (!action_id) return NextResponse.json({ error: 'action_id required' }, { status: 400 });
  if (!['approve', 'skip'].includes(decision ?? '')) {
    return NextResponse.json({ error: 'decision must be "approve" or "skip"' }, { status: 400 });
  }

  const supabase = getSupabase();

  const { data: action, error: fetchErr } = await supabase
    .from('tkg_actions')
    .select('*')
    .eq('id', action_id)
    .eq('user_id', userId)
    .single();

  if (fetchErr || !action) {
    return NextResponse.json({ error: 'Action not found' }, { status: 404 });
  }

  if (decision === 'skip') {
    await supabase
      .from('tkg_actions')
      .update({ status: 'skipped', feedback_weight: -0.5 })
      .eq('id', action_id);

    // Self-feeding loop: write skip as a behavioral signal
    await supabase.from('tkg_signals').insert({
      user_id: userId,
      source: 'user_feedback',
      type: 'rejection',
      content: `Skipped: ${action.directive_text ?? ''}\nReason: ${action.reason ?? ''}`,
      occurred_at: new Date().toISOString(),
    }).then(({ error: sigErr }) => {
      if (sigErr) console.warn('[conviction/execute] feedback signal insert failed:', sigErr.message);
    });

    return NextResponse.json({ status: 'skipped', action_id });
  }

  await supabase
    .from('tkg_actions')
    .update({ status: 'approved', approved_at: new Date().toISOString() })
    .eq('id', action_id);

  // Execute based on artifact in execution_result (generated by artifact-generator)
  const execResult = (action.execution_result as Record<string, unknown>) ?? {};
  const artifact   = execResult.artifact as Record<string, unknown> | undefined;
  let executionResult: Record<string, unknown> = { ...execResult };

  if (artifact) {
    const artifactType = artifact.type as string;
    try {
      switch (artifactType) {
        case 'email': {
          const to      = artifact.to as string | undefined;
          const subject = artifact.subject as string | undefined;
          const msgBody = artifact.body as string | undefined;

          if (to && subject && msgBody && /^[^@]+@[^@]+\.[^@]+$/.test(to)) {
            const useGoogle = await hasIntegration(userId, 'google');
            const result = useGoogle
              ? await sendGmailEmail(userId, { to, subject, body: msgBody })
              : await sendOutlookEmail(userId, { to, subject, body: msgBody });

            const now = new Date().toISOString();
            executionResult = result.success
              ? { ...executionResult, sent: true, sent_at: now }
              : { ...executionResult, sent: false, send_error: result.error };
          }
          break;
        }
        case 'document': {
          // Save document to tkg_signals as a reference (tkg_documents table doesn't exist yet)
          const supabaseDoc = getSupabase();
          await supabaseDoc.from('tkg_signals').insert({
            user_id: userId,
            source: 'artifact',
            type: 'document',
            content: `Document: ${artifact.title}\n\n${(artifact.content as string || '').slice(0, 5000)}`,
            occurred_at: new Date().toISOString(),
          });
          executionResult = { ...executionResult, saved: true, saved_at: new Date().toISOString() };
          break;
        }
        case 'calendar_event': {
          // Calendar API not yet wired — save event details for manual creation
          executionResult = {
            ...executionResult,
            calendar_stub: true,
            title: artifact.title,
            start: artifact.start,
            end: artifact.end,
            description: artifact.description,
          };
          break;
        }
        case 'research_brief': {
          // Save research findings as a signal for future directives
          const supabaseRes = getSupabase();
          await supabaseRes.from('tkg_signals').insert({
            user_id: userId,
            source: 'artifact',
            type: 'research',
            content: `Research: ${artifact.recommended_action}\n\nFindings: ${(artifact.findings as string || '').slice(0, 5000)}`,
            occurred_at: new Date().toISOString(),
          });
          executionResult = { ...executionResult, saved: true, saved_at: new Date().toISOString() };
          break;
        }
        case 'decision_frame': {
          executionResult = { ...executionResult, decided: true, decided_at: new Date().toISOString() };
          break;
        }
        case 'affirmation': {
          executionResult = { ...executionResult, acknowledged: true };
          break;
        }
      }
    } catch (execErr: any) {
      console.error('[conviction/execute] artifact execution error:', execErr.message);
      executionResult = { ...executionResult, exec_error: execErr.message };
    }
  } else {
    // Legacy path: check for old-style draft_type email actions
    const draftType = execResult.draft_type as string | undefined;
    if (draftType === 'email_compose' || draftType === 'email_reply') {
      const to      = execResult.to as string | undefined;
      const subject = execResult.subject as string | undefined;
      const msgBody = execResult.body as string | undefined;

      if (to && subject && msgBody && /^[^@]+@[^@]+\.[^@]+$/.test(to)) {
        const useGoogle = await hasIntegration(userId, 'google');
        const result = useGoogle
          ? await sendGmailEmail(userId, { to, subject, body: msgBody })
          : await sendOutlookEmail(userId, { to, subject, body: msgBody });

        const now = new Date().toISOString();
        executionResult = result.success
          ? { ...executionResult, sent: true, sent_at: now }
          : { ...executionResult, sent: false, send_error: result.error };
      }
    }
  }

  await supabase
    .from('tkg_actions')
    .update({
      status:           'executed',
      executed_at:      new Date().toISOString(),
      execution_result: executionResult,
      feedback_weight:  1.0,
    })
    .eq('id', action_id);

  // Self-feeding loop: write approval as a behavioral signal
  await supabase.from('tkg_signals').insert({
    user_id: userId,
    source: 'user_feedback',
    type: 'approval',
    content: `Approved: ${action.directive_text ?? ''}\nReason: ${action.reason ?? ''}`,
    occurred_at: new Date().toISOString(),
  }).then(({ error: sigErr }) => {
    if (sigErr) console.warn('[conviction/execute] feedback signal insert failed:', sigErr.message);
  });

  return NextResponse.json({ status: 'executed', action_id, result: executionResult });
}

